{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "code-server.fullname" . }}
  labels:
{{ include "code-server.labels.standard" . | indent 4 }}
{{- end -}}